package drivers;

import java.io.IOException;
import java.sql.SQLException;
import java.util.Scanner;

import models.Customer;

public class MainDriver {
	static Scanner keyboard = new Scanner(System.in);
	
	public static void main(String[] args) {
		System.out.println("\n\n*******  WELCOME TO YOUR CDW_SAPP DATA DASHBOARD  *******");
		System.out.println("*********************************************************\n\n");
		
		boolean active = true;
		while (active) {
			System.out.println("PLEASE SELECT A NUMBER FROM THE FOLLOWING OPTIONS\n\n");
			System.out.println("(1) => Display the transactions made by customers living in a given zipcode, for a given month and year\n");
			System.out.println("(2) => Display the total number of transactions & total $ value generated from a given transaction type\n");
			System.out.println("(3) => Display the total number of transactions & total $ value generated by branches in a given state\n");
			System.out.println("(4) => Read the existing account details of a customer\n");
			System.out.println("(5) => Modify the existing account details of a customer\n");
			System.out.println("(6) => Generate the monthly bill on a credit card number for a given month and year\n");
			System.out.println("(7) => Display the transactions made by a distinct customer between 2 distinct dates\n");
			System.out.println("(8) => Exit\n\n");
			
			int option = keyboard.nextInt();
			
			// full user input validations for each case & ESC keystroke to return here / refactor all code for DRYness / re-usable functions please
			try {
				switch (option) {
				case 1:
					TransactionDriver.getTransactionsByZipCode();
					break;
				case 2:
					TransactionDriver.getTotalByType();
					break;
				case 3:
					TransactionDriver.getTotalByState();
					break;
				case 4:
					// add middle name for all customer functional requirements
					CustomerDriver.getCustomerDetails();
					break;
				case 5:
					CustomerDriver.updateCustomerDetails();
					break;
				case 6:
					CustomerDriver.getMonthlyBill();
					break;
				case 7:
					CustomerDriver.getCustTransByDateRange();
					break;
				case 8:
					System.out.println("exiting...");
					active = false;
					System.out.println("Thank you for using the system.");
					break;
				default:
					System.out.println("Please enter a valid option");
					break;
				}
			} catch (Exception e) {
				e.printStackTrace();
			}	
		}
	}

}














